#include "plant_db.h"

namespace godot {

PlantData::PlantData() : ruler(PlanetaryHourCalculator::SUN) {}
PlantData::~PlantData() {}

void PlantData::_bind_methods() {
    ClassDB::bind_method(D_METHOD("set_name", "name"), &PlantData::set_name);
    ClassDB::bind_method(D_METHOD("get_name"), &PlantData::get_name);
    ClassDB::bind_method(D_METHOD("set_ruler", "ruler"), &PlantData::set_ruler);
    ClassDB::bind_method(D_METHOD("get_ruler"), &PlantData::get_ruler);
    ClassDB::bind_method(D_METHOD("set_element", "element"), &PlantData::set_element);
    ClassDB::bind_method(D_METHOD("get_element"), &PlantData::get_element);
    ClassDB::bind_method(D_METHOD("set_properties", "properties"), &PlantData::set_properties);
    ClassDB::bind_method(D_METHOD("get_properties"), &PlantData::get_properties);
    ClassDB::bind_method(D_METHOD("set_sprite_path", "path"), &PlantData::set_sprite_path);
    ClassDB::bind_method(D_METHOD("get_sprite_path"), &PlantData::get_sprite_path);

    ADD_PROPERTY(PropertyInfo(Variant::STRING, "name"), "set_name", "get_name");
    ADD_PROPERTY(PropertyInfo(Variant::INT, "ruler", PROPERTY_HINT_ENUM, "Saturn,Jupiter,Mars,Sun,Venus,Mercury,Moon"), "set_ruler", "get_ruler");
    ADD_PROPERTY(PropertyInfo(Variant::STRING, "element"), "set_element", "get_element");
    ADD_PROPERTY(PropertyInfo(Variant::STRING, "properties"), "set_properties", "get_properties");
    ADD_PROPERTY(PropertyInfo(Variant::STRING, "sprite_path"), "set_sprite_path", "get_sprite_path");
}

namespace {
    static TypedArray<PlantData> get_botanical_entries() {
        static TypedArray<PlantData> entries;
        if (entries.size() > 0) return entries;

        struct RawData {
            String name;
            PlanetaryHourCalculator::Planet ruler;
            String element;
            String props;
            String sprite;
        };

        RawData raw[] = {
            {"Adder's Tongue", PlanetaryHourCalculator::MOON, "Water", "Under the influence of the Moon in the sign of Cancer, it is a most excellent wound herb. The juice of the herb, being boiled in oil, is a singular remedy for all inflammations and hot tumors. It cures by antipathy the diseases of Saturn, and is good for the eyes if applied as a wash.", "res://assets/sprites/plants/Adders-Tongue.png"},
            {"Agrimony", PlanetaryHourCalculator::JUPITER, "Air", "It is an herb under Jupiter and the sign of Cancer. It strengthens the liver, helps the jaundice, and is a singular remedy for the cough. The decoction of the herb made in wine, and drunk, is good against the stings and bitings of venomous beasts.", "res://assets/sprites/plants/Agrimony.png"},
            {"Alkanet", PlanetaryHourCalculator::VENUS, "Earth", "Under the dominion of Venus, it is a singular remedy for all manner of burnings and scaldings. The ointment is excellent for green wounds, and the juice drunk in wine is good for those that have fallen from high places. It stays the humors and strengthens the back.", "res://assets/sprites/plants/Alkanet.png"},
            {"Amara Dulcis", PlanetaryHourCalculator::MERCURY, "Air", "It is an herb of Mercury, and is a singular remedy for the yellow jaundice and all obstructions of the liver and spleen. The decoction of the wood or leaves, being drunk, helps to provoke the terms and eases pains in the stomach. It is also good for those that are troubled with the falling sickness.", "res://assets/sprites/plants/Amara-Dulcis.png"},
            {"Anemone", PlanetaryHourCalculator::MARS, "Fire", "Governed by Mars, the juice of the leaves snuffed up the nose purges the head mightily. It is a powerful remedy for all kinds of ulcers and sores when applied as a plaster. The decoction helps to provoke the terms and is good for the diseases of the kidneys.", "res://assets/sprites/plants/Anemone.png"},
            {"Angelica", PlanetaryHourCalculator::SUN, "Fire", "This is an herb of the Sun in Leo; let it be gathered when he is in that sign. It is an excellent remedy against poison, plague, and all infectious diseases, strengthening the heart exceedingly. The root, being chewed, is a singular remedy for the lungs and stays the fluxes of the belly.", "res://assets/sprites/plants/Angelica.png"},
            {"Archangel", PlanetaryHourCalculator::VENUS, "Air", "An herb of Venus, it is a singular remedy for all kinds of wounds and bruises, making a most excellent ointment. The flowers, made into a conserve, stay the humors and strengthen the stomach. It also helps to drive away melancholy and brings comfort to the heart.", "res://assets/sprites/plants/Archangel.png"},
            {"Arsmart", PlanetaryHourCalculator::MARS, "Fire", "Under the dominion of Mars, it is a powerful remedy for all kinds of wounds and sores, being hot and biting in taste. The juice dropped into the ears helps the deafness, and the herb itself applied to the belly stays the fluxes. It is also good to consume all cold swellings.", "res://assets/sprites/plants/Arsmart.png"},
            {"Asarabacca", PlanetaryHourCalculator::MARS, "Fire", "An herb of Mars, it is a powerful remedy for all kinds of obstructions of the liver and spleen. The decoction made in wine purges by vomit and helps the jaundice and dropsy. It also helps to provoke the terms and eases the pains of the gout.", "res://assets/sprites/plants/Asarabacca.png"},
            {"Ash Tree", PlanetaryHourCalculator::SUN, "Fire", "It is an herb of the Sun, and the berries are a singular remedy for the stone and all diseases of the kidneys. The water distilled from the leaves and berries is good against the bitings of serpents. It also helps to strengthen the head and stays the humors of the stomach.", "res://assets/sprites/plants/Ash-Tree.png"},
            {"Asparagus", PlanetaryHourCalculator::JUPITER, "Air", "Governed by Jupiter, it is a singular remedy for the stone and all diseases of the kidneys and bladder. The decoction of the roots boiled in wine is good for the jaundice and eases the toothache. It also helps to strengthen the head and provokes the terms.", "res://assets/sprites/plants/Asparagus.png"},
            {"Avens", PlanetaryHourCalculator::JUPITER, "Air", "An herb of Jupiter, it is a singular remedy for the stomach and to stay the humors. The root, steeped in wine and drunk, comforts the heart and helps the digestion. It is also excellent for all kinds of wounds and to strengthen the head.", "res://assets/sprites/plants/Avens.png"},
            {"Bay Tree", PlanetaryHourCalculator::SUN, "Fire", "It is an herb of the Sun under Leo, and is a singular remedy against all kinds of poisons and the plague. The oil made of the berries is excellent for all cold griefs of the joints and nerves. It also helps to strengthen the head, memory, and helps the hearing.", "res://assets/sprites/plants/Bay-Tree.png"},
            {"Bedstraw", PlanetaryHourCalculator::VENUS, "Air", "Under the dominion of Venus, it is a singular remedy for all kinds of wounds and sores. The decoction of the herb is good for the stone and to stay the fluxes of the belly. It also helps to stay the humors and to strengthen the stomach.", "res://assets/sprites/plants/Bedstraw.png"},
            {"Beets", PlanetaryHourCalculator::JUPITER, "Earth", "An herb of Jupiter, the juice is a singular remedy for all kinds of obstructions of the liver and spleen. Being snuffed up the nose, it purges the head and helps the headache. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Beets.png"},
            {"Bilberries", PlanetaryHourCalculator::JUPITER, "Earth", "Governed by Jupiter, they are a singular remedy for all kinds of fluxes and to stay the humors of the belly. The juice of the berries is good for the heat of the liver and stomach. It also helps to strengthen the head and restores the appetite.", "res://assets/sprites/plants/Bilberries.png"},
            {"Birch Tree", PlanetaryHourCalculator::VENUS, "Water", "An herb of Venus, the juice or sap is a singular remedy for the stone and all diseases of the kidneys. The decoction of the leaves is good for the itch and all hot eruptions of the skin. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Birch-Tree.png"},
            {"Birthwort", PlanetaryHourCalculator::MARS, "Fire", "Under the dominion of Mars, it is a powerful remedy for all kinds of wounds and sores. The decoction of the root helps to provoke the terms and eases the pains of the mother. It also helps to draw out thorns or splinters from the flesh.", "res://assets/sprites/plants/Birthwort.png"},
            {"Bishop's Weed", PlanetaryHourCalculator::VENUS, "Earth", "An herb of Venus, it is a singular remedy for all kinds of wounds and sores, and helps to consume all windiness. The juice drunk in wine is good against the bitings of venomous beasts. It also helps to stay the humors and to strengthen the stomach.", "res://assets/sprites/plants/Bishops-Weed.png"},
            {"Bistort", PlanetaryHourCalculator::SATURN, "Earth", "Governed by Saturn, it is a powerful remedy for all kinds of fluxes and to stay the humors of the belly. The root, made into a powder, is excellent for all kinds of wounds and to stay bleeding. It also helps to strengthen the head and resists the plague.", "res://assets/sprites/plants/Bistort.png"},
            {"Bluebottle", PlanetaryHourCalculator::SATURN, "Earth", "An herb of Saturn, it is a powerful remedy for all kinds of wounds and sores. The juice of the flowers dropped into the eyes helps the inflammations and clears the sight. It also helps to stay the humors and to strengthen the stomach.", "res://assets/sprites/plants/Bluebottle.png"},
            {"Borrage", PlanetaryHourCalculator::JUPITER, "Air", "Under the influence of Jupiter, it is a singular remedy for the heart and to drive away melancholy. The flowers, made into a conserve, comfort the spirits and help the fainting heart. It also helps to strengthen the head and restores the vital heat.", "res://assets/sprites/plants/Borrage.png"},
            {"Bramble", PlanetaryHourCalculator::VENUS, "Water", "An herb of Venus under Aries, it is a singular remedy for all kinds of wounds and sores. The decoction of the leaves or berries stays the fluxes of the belly and strengthens the gums. It also helps to stay the humors and to strengthen the stomach.", "res://assets/sprites/plants/Bramble.png"},
            {"Briony", PlanetaryHourCalculator::MARS, "Fire", "Governed by Mars, it is a powerful remedy for all kinds of obstructions of the liver and spleen. The root, being applied as a plaster, draws out splinters and helps all hard swellings. It also helps to provoke the terms and purges the body of phlegm.", "res://assets/sprites/plants/Briony.png"},
            {"Brooklime", PlanetaryHourCalculator::MARS, "Water", "Under the dominion of Mars, it is a powerful remedy for all kinds of obstructions of the liver and spleen. The decoction helps the scurvy and provokes the terms. It also helps to stay the humors and eases the pains of the stone.", "res://assets/sprites/plants/Brooklime.png"},
            {"Butcher's Broom", PlanetaryHourCalculator::MARS, "Earth", "An herb of Mars, it is a powerful remedy for all kinds of obstructions of the liver and spleen. The decoction of the roots in wine is good for the stone and all diseases of the kidneys. It also helps to provoke the terms and opens the lungs.", "res://assets/sprites/plants/Butchers-Broom.png"},
            {"Cabbages", PlanetaryHourCalculator::MOON, "Water", "Governed by the Moon, they are a singular remedy for all kinds of wounds and sores. The juice mixed with honey helps the hoarseness and the cough. It also helps to stay the humors and to strengthen the stomach after much drinking.", "res://assets/sprites/plants/Cabbages.png"},
            {"Calamint", PlanetaryHourCalculator::MERCURY, "Air", "An herb of Mercury, it is a singular remedy for all kinds of obstructions of the liver and spleen. The decoction helps the cough and provokes the terms. It also helps to stay the humors and to strengthen the stomach.", "res://assets/sprites/plants/Calamint.png"},
            {"Camomile", PlanetaryHourCalculator::SUN, "Fire", "Under the influence of the Sun, it is a singular remedy for all kinds of pains and to stay the humors. The decoction is excellent for the stone and eases the pains of the belly. It also helps to strengthen the head and comforts the nerves.", "res://assets/sprites/plants/Camomile.png"},
            {"Celandine", PlanetaryHourCalculator::SUN, "Fire", "Governed by the Sun, it is a singular remedy for the eyes and to help the sight. The juice mixed with honey and boiled in a brass vessel is excellent for all films that hinder the vision. It also helps to strengthen the head and helps the jaundice.", "res://assets/sprites/plants/Celandine.png"},
            {"Centaury", PlanetaryHourCalculator::SUN, "Fire", "An herb of the Sun, it is a singular remedy for all kinds of obstructions of the liver and spleen. The decoction helps to provoke the terms and kills the worms of the belly. It also helps to strengthen the head and cures the agues.", "res://assets/sprites/plants/Centaury.png"},
            {"Chervil", PlanetaryHourCalculator::JUPITER, "Air", "Under the dominion of Jupiter, it is a singular remedy for the stone and to stay the humors. The decoction of the herb helps the digestion and provokes the terms. It also helps to strengthen the head and eases the pains of the stomach.", "res://assets/sprites/plants/Chervil.png"},
            {"Chestnut Tree", PlanetaryHourCalculator::JUPITER, "Earth", "Governed by Jupiter, the fruit is a singular remedy for all kinds of fluxes and to stay the humors. The decoction of the bark is good for the cough and to stay the bleeding. It also helps to strengthen the head and restores the body.", "res://assets/sprites/plants/Chestnut-Tree.png"},
            {"Chickweed", PlanetaryHourCalculator::MOON, "Water", "An herb of the Moon, it is a singular remedy for all kinds of wounds and sores. Applied as a plaster, it cools all hot inflammations and swellings. It also helps to stay the humors and to strengthen the stomach.", "res://assets/sprites/plants/Chickweed.png"},
            {"Cinquefoil", PlanetaryHourCalculator::JUPITER, "Earth", "Under the influence of Jupiter, it is a singular remedy for all kinds of fluxes and to stay the humors. The decoction of the root in wine helps the jaundice and the cough. It also helps to strengthen the head and cures all inflammations.", "res://assets/sprites/plants/Cinquefoil.png"},
            {"Clary", PlanetaryHourCalculator::MOON, "Water", "Governed by the Moon, it is a singular remedy for the eyes and to help the sight. The seed put into the eyes clears them of all motes and films. It also helps to strengthen the head and provokes the terms.", "res://assets/sprites/plants/Clary.png"},
            {"Cleavers", PlanetaryHourCalculator::MOON, "Water", "An herb of the Moon, it is a singular remedy for all kinds of wounds and sores. The juice of the herb is good for the bitings of snakes and venomous beasts. It also helps to stay the humors and to strengthen the stomach.", "res://assets/sprites/plants/Cleavers.png"},
            {"Coltsfoot", PlanetaryHourCalculator::VENUS, "Water", "Under the dominion of Venus, it is a singular remedy for the lungs and to help the cough. The smoke of the dried leaves, being sucked through a pipe, helps the shortness of breath. It also helps to strengthen the head and stays the hot humors.", "res://assets/sprites/plants/Coltsfoot.png"},
            {"Comfrey", PlanetaryHourCalculator::SATURN, "Earth", "Under the heavy dominion of Saturn, it is commonly known as knit-bone. It excels at mending fractures and healing deep wounds when applied as a plaster. The decoction of the root in wine is good for all internal bleedings and to stay the humors.", "res://assets/sprites/plants/Comfrey.png"},
            {"Costmary", PlanetaryHourCalculator::JUPITER, "Air", "Governed by Jupiter, it is a singular remedy for the stomach and to stay the humors. The decoction helps to provoke the terms and kills the worms of the belly. It also helps to strengthen the head and drives away melancholy.", "res://assets/sprites/plants/Costmary.png"},
            {"Cowslips", PlanetaryHourCalculator::VENUS, "Air", "An herb of Venus under Aries, it is a singular remedy for all kinds of pains and to stay the humors. The flowers, made into a conserve, are excellent for the nerves and help the palsy. It also helps to strengthen the head and restores the memory.", "res://assets/sprites/plants/Cowslips.png"},
            {"Cudweed", PlanetaryHourCalculator::VENUS, "Earth", "Under the dominion of Venus, it is a singular remedy for all kinds of fluxes and to stay the humors. The decoction is good for the quinsey and all inflammations of the throat. It also helps to strengthen the head and stays the bleeding.", "res://assets/sprites/plants/Cudweed.png"},
            {"Currants", PlanetaryHourCalculator::VENUS, "Water", "Governed by Venus, they are a singular remedy for all kinds of fluxes and to stay the humors of the stomach. The juice of the berries cools the heat of the liver and stomach. It also helps to strengthen the head and restores the appetite.", "res://assets/sprites/plants/Currants.png"},
            {"Daisy", PlanetaryHourCalculator::VENUS, "Water", "An herb of Venus under Cancer, it is a singular remedy for all kinds of wounds and sores. The decoction of the leaves and flowers is good for the pleurisy and all internal pains. It also helps to stay the humors and to strengthen the stomach.", "res://assets/sprites/plants/Daisy.png"},
            {"Dandelion", PlanetaryHourCalculator::JUPITER, "Air", "Under the influence of Jupiter, it is singularly powerful for cleansing the liver and kidneys. The decoction of the root helps the jaundice and the stone. It also helps to strengthen the head and purges the blood of all ill humors.", "res://assets/sprites/plants/Dandelion.png"},
            {"Devil's Bit", PlanetaryHourCalculator::VENUS, "Earth", "Governed by Venus, it is a singular remedy for all kinds of wounds and sores. The decoction helps the plague and all infectious diseases. It also helps to stay the humors and to strengthen the stomach.", "res://assets/sprites/plants/Devils-Bit.png"},
            {"Dock", PlanetaryHourCalculator::JUPITER, "Earth", "An herb of Jupiter, it is a singular remedy for all kinds of obstructions of the liver and spleen. The decoction of the root helps the jaundice and the itch. It also helps to strengthen the head and cleanses the blood.", "res://assets/sprites/plants/Dock.png"},
            {"Dropwort", PlanetaryHourCalculator::VENUS, "Earth", "Under the dominion of Venus, it is a singular remedy for the stone and all diseases of the kidneys. The decoction of the root in wine helps the jaundice and provokes the terms. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Dropwort.png"},
            {"Elder Tree", PlanetaryHourCalculator::VENUS, "Water", "Governed by Venus, the berries are a singular remedy for all kinds of fluxes and to stay the humors. The decoction of the bark is good for the dropsy and the jaundice. It also helps to strengthen the head and clears the skin of all blemishes.", "res://assets/sprites/plants/Elder-Tree.png"},
            {"Elm Tree", PlanetaryHourCalculator::SATURN, "Earth", "Under the dominion of Saturn, it is a powerful remedy for all kinds of wounds and sores. The decoction of the bark is excellent for all hot inflammations and swellings. It also helps to stay the humors and to strengthen the stomach.", "res://assets/sprites/plants/Elm-Tree.png"},
            {"Endive", PlanetaryHourCalculator::VENUS, "Water", "Governed by Venus, it is a singular remedy for all kinds of obstructions of the liver and spleen. The juice cools the heat of the stomach and liver. It also helps to strengthen the head and stays the hot humors.", "res://assets/sprites/plants/Endive.png"},
            {"Eyebright", PlanetaryHourCalculator::SUN, "Air", "An herb of the Sun in Leo, it is the best herb to help the sight. The juice dropped into the eyes, or the decoction drunk, has been known to restore vision to the aged. It also helps to strengthen the head and restores the memory.", "res://assets/sprites/plants/Eyebright.png"},
            {"Fennel", PlanetaryHourCalculator::MERCURY, "Air", "Under the influence of Mercury under Virgo, it is a singular remedy for the eyes and to help the sight. The decoction helps the digestion and provokes the terms. It also helps to strengthen the head and comforts the stomach.", "res://assets/sprites/plants/Fennel.png"},
            {"Fig Tree", PlanetaryHourCalculator::JUPITER, "Air", "Governed by Jupiter under Aries, it is a singular remedy for all kinds of fluxes and to stay the humors. The decoction of the leaves is good for the cough and the shortness of breath. It also helps to strengthen the head and restores the body.", "res://assets/sprites/plants/Fig-Tree.png"},
            {"Flax", PlanetaryHourCalculator::MERCURY, "Air", "An herb of Mercury, the seed is a singular remedy for the stone and all diseases of the kidneys. Applied as a plaster, it eases all pains and inflammations. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Flax.png"},
            {"Foxglove", PlanetaryHourCalculator::VENUS, "Water", "Under the dominion of Venus, it is a singular remedy for all kinds of wounds and sores. The decoction purges the body of all sharp and thin humors. It also helps to strengthen the head and stays the hot humors.", "res://assets/sprites/plants/Foxglove.png"},
            {"Fumitory", PlanetaryHourCalculator::SATURN, "Earth", "Governed by Saturn, it is a powerful remedy for all kinds of obstructions of the liver and spleen. The decoction helps the jaundice and the scurvy. It also helps to strengthen the head and clears the blood.", "res://assets/sprites/plants/Fumitory.png"},
            {"Furze Bush", PlanetaryHourCalculator::MARS, "Fire", "An herb of Mars, it is a powerful remedy for the stone and all diseases of the kidneys. The decoction of the flowers helps the jaundice and provokes the terms. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Furze-Bush.png"},
            {"Garlic", PlanetaryHourCalculator::MARS, "Fire", "Under the influence of Mars, it is a powerful remedy against all poisons and the biting of mad dogs. The decoction helps the cough and opens the obstructions of the lungs. It also helps to strengthen the head and drives away the plague.", "res://assets/sprites/plants/Garlic.png"},
            {"Gladwin", PlanetaryHourCalculator::SATURN, "Earth", "Governed by Saturn, it is a powerful remedy for all kinds of obstructions of the liver and spleen. The decoction of the root helps the cough and provokes the terms. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Gladwin.png"},
            {"Golden Rod", PlanetaryHourCalculator::VENUS, "Air", "An herb of Venus, it is a singular remedy for all kinds of wounds and sores. The decoction is excellent for the stone and all diseases of the kidneys. It also helps to stay the humors and to strengthen the stomach.", "res://assets/sprites/plants/Golden-Rod.png"},
            {"Gooseberry", PlanetaryHourCalculator::VENUS, "Water", "Under the dominion of Venus, it is a singular remedy for all kinds of fluxes and to stay the humors. The juice cools the heat of the stomach and liver. It also helps to strengthen the head and restores the appetite.", "res://assets/sprites/plants/Gooseberry.png"},
            {"Groundsel", PlanetaryHourCalculator::VENUS, "Water", "Governed by Venus under Cancer, it is a singular remedy for all kinds of pains and to stay the humors. The decoction helps the jaundice and eases the pains of the stomach. It also helps to strengthen the head and stays the bleeding.", "res://assets/sprites/plants/Groundsel.png"},
            {"Heart's Ease", PlanetaryHourCalculator::SATURN, "Air", "An herb of Saturn, it is a powerful remedy for all kinds of pains and to stay the humors. The decoction is good for the pleurisy and all inflammations of the lungs. It also helps to strengthen the head and comforts the heart.", "res://assets/sprites/plants/Hearts-Ease.png"},
            {"Hemlock", PlanetaryHourCalculator::SATURN, "Water", "Governed by Saturn, it is exceedingly cold and dangerous if taken inwardly. Applied outwardly as a plaster, it helps all hot inflammations and swellings. It also helps to stay the humors and eases the pains of the gout.", "res://assets/sprites/plants/Hemlock.png"},
            {"Henbane", PlanetaryHourCalculator::SATURN, "Water", "Under the dominion of Saturn, it is a powerful narcotic and eases all pains. Applied as a plaster, it helps all hot inflammations and the pains of the gout. It also helps to stay the humors and to strengthen the stomach.", "res://assets/sprites/plants/Henbane.png"},
            {"Herb Robert", PlanetaryHourCalculator::VENUS, "Earth", "Governed by Venus, it is a singular remedy for all kinds of wounds and sores. The decoction helps the stone and all diseases of the kidneys. It also helps to stay the humors and to strengthen the stomach.", "res://assets/sprites/plants/Herb-Robert.png"},
            {"Holly", PlanetaryHourCalculator::SATURN, "Fire", "An herb of Saturn, it is a powerful remedy for the stone and all diseases of the kidneys. The decoction of the berries helps the colic and stays the fluxes. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Holly.png"},
            {"Honeysuckle", PlanetaryHourCalculator::MERCURY, "Air", "Under the influence of Mercury, it is a singular remedy for the lungs and to help the cough. The decoction of the flowers helps to provoke the terms and eases the pains of the stomach. It also helps to strengthen the head and restores the memory.", "res://assets/sprites/plants/Honeysuckle.png"},
            {"Horehound", PlanetaryHourCalculator::MERCURY, "Air", "Governed by Mercury, it is a singular remedy for the lungs and to help the cough. The decoction helps the jaundice and all obstructions of the liver. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Horehound.png"},
            {"Horsetail", PlanetaryHourCalculator::SATURN, "Earth", "An herb of Saturn, it is a powerful remedy for all kinds of fluxes and to stay the humors. The decoction helps the stone and all diseases of the kidneys. It also helps to strengthen the head and stays the bleeding.", "res://assets/sprites/plants/Horsetail.png"},
            {"Houseleek", PlanetaryHourCalculator::JUPITER, "Water", "Governed by Jupiter, it is exceedingly cold and quenching. Applied outwardly, it is excellent against all hot inflammations, burnings, and scaldings. It also helps to strengthen the head and preserves the house from lightning.", "res://assets/sprites/plants/Houseleek.png"},
            {"Hyssop", PlanetaryHourCalculator::JUPITER, "Fire", "Under the influence of Jupiter, it is a singular remedy for the lungs and to help the cough. The decoction mixed with honey helps the shortness of breath. It also helps to stay the humors and to strengthen the stomach.", "res://assets/sprites/plants/Hyssop.png"},
            {"Ivy", PlanetaryHourCalculator::SATURN, "Water", "Governed by Saturn, it is a powerful remedy for all kinds of wounds and sores. The decoction of the berries helps the jaundice and the stone. It also helps to stay the humors and to strengthen the stomach.", "res://assets/sprites/plants/Ivy.png"},
            {"Juniper", PlanetaryHourCalculator::MARS, "Fire", "An herb of Mars, it is a powerful remedy against all kinds of poisons and the plague. The berries comfort the stomach and help the digestion. It also helps to strengthen the head and restores the memory.", "res://assets/sprites/plants/Juniper.png"},
            {"Kidneywort", PlanetaryHourCalculator::VENUS, "Water", "Under the dominion of Venus under Libra, it is a singular remedy for the stone and all diseases of the kidneys. The juice cools all hot inflammations and swellings. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Kidneywort.png"},
            {"Knapweed", PlanetaryHourCalculator::SATURN, "Earth", "Governed by Saturn, it is a powerful remedy for all kinds of fluxes and to stay the humors. The decoction is good for the cough and to stay the bleeding. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Knapweed.png"},
            {"Knotgrass", PlanetaryHourCalculator::SATURN, "Earth", "An herb of Saturn, it is a powerful remedy for all kinds of fluxes and to stay the humors. The decoction helps the stone and all diseases of the kidneys. It also helps to strengthen the head and stays the bleeding.", "res://assets/sprites/plants/Knotgrass.png"},
            {"Ladies' Mantle", PlanetaryHourCalculator::VENUS, "Earth", "Under the dominion of Venus, it is a singular remedy for all kinds of wounds and sores. The decoction stays the fluxes and strengthens the stomach. It also helps to stay the humors and to strengthen the body.", "res://assets/sprites/plants/Ladies-Mantle.png"},
            {"Ladies' Slipper", PlanetaryHourCalculator::VENUS, "Water", "Governed by Venus, it is a singular remedy for all kinds of pains and to stay the humors. The decoction helps the nerves and eases the pains of the head. It also helps to strengthen the head and comforts the spirits.", "res://assets/sprites/plants/Ladies-Slipper.png"},
            {"Lavender", PlanetaryHourCalculator::MERCURY, "Air", "Ruled by Mercury and under the Air element, it is highly aromatic. The decoction helps the headache and restores the nervous energy. It also helps to strengthen the head and comforts the heart.", "res://assets/sprites/plants/Lavender.png"},
            {"Lemon Balm", PlanetaryHourCalculator::JUPITER, "Air", "Governed by Jupiter under Cancer, it causes the mind and heart to become merry. The decoction revives the fainting spirits and drives away melancholy. It also helps to strengthen the head and restores the memory.", "res://assets/sprites/plants/Lemon-Balm.png"},
            {"Lettuce", PlanetaryHourCalculator::MOON, "Water", "An herb of the Moon, it is exceedingly cold and quenching. The juice helps to cause sleep and cools all hot inflammations. It also helps to stay the humors and to strengthen the stomach.", "res://assets/sprites/plants/Lettuce.png"},
            {"Lily of the Valley", PlanetaryHourCalculator::MERCURY, "Air", "Under the influence of Mercury, it is a singular remedy for the brain and memory. The water distilled from the flowers helps the palsy and all diseases of the nerves. It also helps to strengthen the head and restores the spirits.", "res://assets/sprites/plants/Lily-of-the-Valley.png"},
            {"Liquorice", PlanetaryHourCalculator::MERCURY, "Air", "Governed by Mercury, it is a singular remedy for the lungs and to help the cough. The decoction helps the heat of the stomach and liver. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Liquorice.png"},
            {"Liverwort", PlanetaryHourCalculator::JUPITER, "Water", "An herb of Jupiter under Cancer, it is a singular remedy for the liver and to help the yellow jaundice. The decoction helps all obstructions of the liver and spleen. It also helps to strengthen the head and stays the hot humors.", "res://assets/sprites/plants/Liverwort.png"},
            {"Loosestrife", PlanetaryHourCalculator::MOON, "Water", "Governed by the Moon, it is a singular remedy for all kinds of fluxes and to stay the humors. The decoction helps the cough and to stay the bleeding. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Loosestrife.png"},
            {"Lovage", PlanetaryHourCalculator::SUN, "Fire", "Under the influence of the Sun, it is a singular remedy for the stomach and to stay the humors. The decoction helps the digestion and provokes the terms. It also helps to strengthen the head and restores the body.", "res://assets/sprites/plants/Lovage.png"},
            {"Madder", PlanetaryHourCalculator::MARS, "Fire", "Governed by Mars, it is a powerful remedy for all kinds of obstructions of the liver and spleen. The decoction helps the jaundice and the stone. It also helps to provoke the terms and stays the fluxes.", "res://assets/sprites/plants/Madder.png"},
            {"Maidenhair", PlanetaryHourCalculator::MERCURY, "Air", "An herb of Mercury, it is a singular remedy for the lungs and to help the cough. The decoction helps the stone and provokes the terms. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Maidenhair.png"},
            {"Mallows", PlanetaryHourCalculator::VENUS, "Water", "Under the dominion of Venus, they are a singular remedy for all kinds of pains and to stay the humors. The decoction helps the stone and all diseases of the kidneys. It also helps to strengthen the head and stays the hot humors.", "res://assets/sprites/plants/Mallows.png"},
            {"Mandrake", PlanetaryHourCalculator::SATURN, "Earth", "Governed by Saturn, it is a powerful narcotic and causes sleep. Applied as a plaster, it eases all pains and helps all hard swellings. It also helps to stay the humors and to strengthen the stomach.", "res://assets/sprites/plants/Mandrake.png"},
            {"Marigold", PlanetaryHourCalculator::SUN, "Fire", "An herb of the Sun under Leo, it strengthens the heart exceedingly. The flowers are a singular remedy against the plague and all infectious diseases. It also helps the sight and comforts the head.", "res://assets/sprites/plants/Marigold.png"},
            {"Masterwort", PlanetaryHourCalculator::MARS, "Fire", "Governed by Mars, it is a powerful remedy against all kinds of poisons and the plague. The decoction helps the cough and provokes the terms. It also helps to strengthen the head and restores the vital heat.", "res://assets/sprites/plants/Masterwort.png"},
            {"Meadowsweet", PlanetaryHourCalculator::VENUS, "Air", "Under the dominion of Venus, it is a singular remedy for the heart and to drive away melancholy. The decoction helps the heat of the stomach and liver. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Meadowsweet.png"},
            {"Medlar", PlanetaryHourCalculator::SATURN, "Earth", "Governed by Saturn, the fruit is a singular remedy for all kinds of fluxes and to stay the humors. The decoction of the leaves is good for the cough and to stay the bleeding. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Medlar.png"},
            {"Mint", PlanetaryHourCalculator::VENUS, "Air", "An herb of Venus, it is a singular remedy for the stomach and to stay the humors. The decoction helps the digestion and stays the vomiting. It also helps to strengthen the head and restores the body.", "res://assets/sprites/plants/Mint.png"},
            {"Mistletoe", PlanetaryHourCalculator::SUN, "Air", "Under the influence of the Sun, it is a singular remedy for the falling sickness and all diseases of the brain. The decoction helps the palsy and comforts the nerves. It also helps to strengthen the head and restores the memory.", "res://assets/sprites/plants/Mistletoe.png"},
            {"Moneywort", PlanetaryHourCalculator::VENUS, "Water", "Governed by Venus, it is a singular remedy for all kinds of wounds and sores. The decoction stays the fluxes and strengthens the stomach. It also helps to stay the humors and to strengthen the body.", "res://assets/sprites/plants/Moneywort.png"},
            {"Moonwort", PlanetaryHourCalculator::MOON, "Water", "An herb of the Moon, it is a singular remedy for all kinds of wounds and bruises. It is said to have the power to open locks and unshoe horses that tread upon it. It also helps to stay the humors and stays the bleeding.", "res://assets/sprites/plants/Moonwort.png"},
            {"Moss", PlanetaryHourCalculator::SATURN, "Earth", "Governed by Saturn, it is a powerful remedy for all kinds of fluxes and to stay the humors. The decoction is good for the stone and all diseases of the kidneys. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Moss.png"},
            {"Motherwort", PlanetaryHourCalculator::VENUS, "Earth", "Under the dominion of Venus under Leo, it is a singular remedy for the heart and to drive away melancholy. The decoction helps the shortness of breath and provokes the terms. It also helps to strengthen the head and restores the spirits.", "res://assets/sprites/plants/Motherwort.png"},
            {"Mouse-ear", PlanetaryHourCalculator::MOON, "Water", "Governed by the Moon, it is a singular remedy for all kinds of fluxes and to stay the humors. The decoction helps the cough and to stay the bleeding. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Mouse-ear.png"},
            {"Mugwort", PlanetaryHourCalculator::MOON, "Water", "An herb of the Moon under the Water element, it is excellent for clearing obstructions. The decoction helps to provoke the terms and eases the pains of the mother. It also helps to induce vivid dreams and aids female complaints.", "res://assets/sprites/plants/Mugwort.png"},
            {"Mulberry Tree", PlanetaryHourCalculator::MERCURY, "Air", "Governed by Mercury, it is a singular remedy for the throat and to help the cough. The juice of the berries stays the fluxes and strengthens the stomach. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Mulberry-Tree.png"},
            {"Mullein", PlanetaryHourCalculator::SATURN, "Earth", "Under the dominion of Saturn, it is a powerful remedy for all kinds of pains and to stay the humors. The decoction helps the cough and all diseases of the lungs. It also helps to strengthen the head and eases the pains of the joints.", "res://assets/sprites/plants/Mullein.png"},
            {"Mustard", PlanetaryHourCalculator::MARS, "Fire", "Governed by Mars, it is a powerful remedy to provoke the terms and to help the cough. The decoction helps the sciatica and eases the pains of the joints. It also helps to strengthen the head and restores the body.", "res://assets/sprites/plants/Mustard.png"},
            {"Navelwort", PlanetaryHourCalculator::VENUS, "Water", "An herb of Venus, it is a singular remedy for all kinds of hot inflammations and to stay the humors. The decoction helps the stone and all diseases of the kidneys. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Navelwort.png"},
            {"Nettle", PlanetaryHourCalculator::MARS, "Fire", "Governed by Mars under the Fire element, it is hot and dry. The decoction is excellent for purifying the blood and stimulating vitality. It also helps to ease joint pain and opens the obstructions of the lungs.", "res://assets/sprites/plants/Nettle.png"},
            {"Nightshade", PlanetaryHourCalculator::SATURN, "Water", "Under the dominion of Saturn, it is very cold and used to cool all hot inflammations. The decoction stays the sharpness of humors and helps all hot swellings. It must be used with great caution as it is dangerous if taken inwardly.", "res://assets/sprites/plants/Nightshade.png"},
            {"Oak Tree", PlanetaryHourCalculator::JUPITER, "Earth", "Governed by Jupiter, it is a singular remedy for all kinds of fluxes and to stay the humors. The decoction of the bark stays the bleeding and strengthens the stomach. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Oak-Tree.png"},
            {"Oats", PlanetaryHourCalculator::VENUS, "Earth", "An herb of Venus, they are a singular remedy for all kinds of fluxes and to stay the humors. The decoction helps the heat of the stomach and liver. It also helps to strengthen the head and restores the body.", "res://assets/sprites/plants/Oats.png"},
            {"Onions", PlanetaryHourCalculator::MARS, "Fire", "Governed by Mars, they are a powerful remedy to provoke the terms and to help the cough. The juice helps the bitings of mad dogs and serpents. It also helps to strengthen the head and opens the obstructions.", "res://assets/sprites/plants/Onions.png"},
            {"Orpine", PlanetaryHourCalculator::MOON, "Water", "Under the influence of the Moon, it is a singular remedy for all kinds of wounds and sores. The decoction stays the fluxes and strengthens the stomach. It also helps to stay the humors and to strengthen the body.", "res://assets/sprites/plants/Orpine.png"},
            {"Parsley", PlanetaryHourCalculator::MERCURY, "Air", "Governed by Mercury, it is a singular remedy for the stone and to provoke the terms. The decoction helps the jaundice and all obstructions of the liver. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Parsley.png"},
            {"Parsnip", PlanetaryHourCalculator::VENUS, "Earth", "An herb of Venus, it is a singular remedy for the stomach and to stay the humors. The decoction helps the digestion and provokes the terms. It also helps to strengthen the head and restores the body.", "res://assets/sprites/plants/Parsnip.png"},
            {"Peach Tree", PlanetaryHourCalculator::VENUS, "Water", "Governed by Venus, the blossoms are a singular remedy for all kinds of fluxes and to stay the humors. The decoction of the leaves helps the cough and all diseases of the lungs. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Peach-Tree.png"},
            {"Pear Tree", PlanetaryHourCalculator::VENUS, "Water", "Under the dominion of Venus, it is a singular remedy for the stomach and to stay the humors. The fruit stays the fluxes and strengthens the stomach. It also helps to strengthen the head and restores the body.", "res://assets/sprites/plants/Pear-Tree.png"},
            {"Pellitory of Spain", PlanetaryHourCalculator::MERCURY, "Air", "Governed by Mercury, it is a singular remedy for the brain and memory. The root chewed in the mouth helps the toothache and the palsy. It also helps to strengthen the head and restores the spirits.", "res://assets/sprites/plants/Pellitory-of-Spain.png"},
            {"Pellitory of the Wall", PlanetaryHourCalculator::MERCURY, "Air", "An herb of Mercury, it is a singular remedy for the stone and to stay the humors. The decoction helps the cough and all diseases of the lungs. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Pellitory-of-the-Wall.png"},
            {"Pennyroyal", PlanetaryHourCalculator::VENUS, "Air", "Governed by Venus, it is a singular remedy for the lungs and to help the cough. The decoction helps the jaundice and provokes the terms. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Pennyroyal.png"},
            {"Peony", PlanetaryHourCalculator::SUN, "Fire", "Under the influence of the Sun, the root is a singular remedy for the falling sickness. The decoction helps the nightmare and all melancholy dreams. It also helps to strengthen the head and restores the spirits.", "res://assets/sprites/plants/Peony.png"},
            {"Pepper", PlanetaryHourCalculator::MARS, "Fire", "Governed by Mars, it is a powerful remedy against all kinds of poisons and the plague. The decoction helps the cough and all diseases of the lungs. It also helps to strengthen the head and restores the vital heat.", "res://assets/sprites/plants/Pepper.png"},
            {"Periwinkle", PlanetaryHourCalculator::VENUS, "Water", "An herb of Venus, it is a singular remedy for all kinds of fluxes and to stay the humors. The decoction stays the bleeding and strengthens the stomach. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Periwinkle.png"},
            {"Pine Tree", PlanetaryHourCalculator::MARS, "Fire", "Governed by Mars, the kernels are a singular remedy for the lungs and to help the cough. The decoction helps the stone and all diseases of the kidneys. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Pine-Tree.png"},
            {"Plantain", PlanetaryHourCalculator::VENUS, "Earth", "Under the dominion of Venus, it is a singular remedy for all kinds of wounds and sores. The decoction stays the fluxes and strengthens the stomach. It also helps to stay the humors and to strengthen the body.", "res://assets/sprites/plants/Plantain.png"},
            {"Plum Tree", PlanetaryHourCalculator::VENUS, "Water", "Governed by Venus, it is a singular remedy for the stomach and to stay the humors. The fruit stays the fluxes and strengthens the stomach. It also helps to strengthen the head and restores the body.", "res://assets/sprites/plants/Plum-Tree.png"},
            {"Polypody", PlanetaryHourCalculator::SATURN, "Earth", "An herb of Saturn, it is a powerful remedy for all kinds of obstructions of the liver and spleen. The decoction helps the jaundice and the stone. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Polypody.png"},
            {"Poplar Tree", PlanetaryHourCalculator::SATURN, "Water", "Governed by Saturn, it is a powerful remedy for all kinds of pains and to stay the humors. The decoction of the bark helps the sciatica and eases the pains of the joints. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Poplar-Tree.png"},
            {"Poppy", PlanetaryHourCalculator::MOON, "Water", "Under the influence of the Moon, it is very cold and causes sleep. The white poppy is better for the head, and the black for the stomach. It also helps to stay the humors and eases all kinds of pains.", "res://assets/sprites/plants/Poppy.png"},
            {"Primrose", PlanetaryHourCalculator::VENUS, "Earth", "Governed by Venus, it is a singular remedy for all kinds of pains and to stay the humors. The decoction helps the nerves and eases the pains of the head. It also helps to strengthen the head and restores the spirits.", "res://assets/sprites/plants/Primrose.png"},
            {"Privet", PlanetaryHourCalculator::MOON, "Water", "An herb of the Moon, it is a singular remedy for all kinds of fluxes and to stay the humors. The decoction stays the bleeding and strengthens the stomach. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Privet.png"},
            {"Purslane", PlanetaryHourCalculator::MOON, "Water", "Governed by the Moon, it is exceedingly cold and quenching. The juice helps to cause sleep and cools all hot inflammations. It also helps to stay the humors and to strengthen the stomach.", "res://assets/sprites/plants/Purslane.png"},
            {"Quince Tree", PlanetaryHourCalculator::SATURN, "Earth", "Under the dominion of Saturn, it is a powerful remedy for the stomach and to stay the humors. The fruit stays the fluxes and strengthens the stomach. It also helps to strengthen the head and restores the body.", "res://assets/sprites/plants/Quince-Tree.png"},
            {"Radish", PlanetaryHourCalculator::MARS, "Fire", "Governed by Mars, it is a powerful remedy for the stone and to provoke the terms. The decoction helps the cough and all diseases of the lungs. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Radish.png"},
            {"Ragwort", PlanetaryHourCalculator::VENUS, "Water", "An herb of Venus, it is a singular remedy for all kinds of wounds and sores. The decoction stays the fluxes and strengthens the stomach. It also helps to stay the humors and to strengthen the body.", "res://assets/sprites/plants/Ragwort.png"},
            {"Raspberry", PlanetaryHourCalculator::VENUS, "Water", "Governed by Venus, it is a singular remedy for the stomach and to stay the humors. The fruit stays the fluxes and strengthens the stomach. It also helps to strengthen the head and restores the body.", "res://assets/sprites/plants/Raspberry.png"},
            {"Rhubarb", PlanetaryHourCalculator::MARS, "Fire", "Under the influence of Mars, it is a powerful remedy for all kinds of obstructions of the liver and spleen. The decoction helps the jaundice and the stone. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Rhubarb.png"},
            {"Rice", PlanetaryHourCalculator::SUN, "Water", "Governed by the Sun, it is a singular remedy for all kinds of fluxes and to stay the humors. The decoction helps the heat of the stomach and liver. It also helps to strengthen the head and restores the body.", "res://assets/sprites/plants/Rice.png"},
            {"Rockets", PlanetaryHourCalculator::MARS, "Fire", "An herb of Mars, they are a powerful remedy to provoke the terms and to help the cough. The decoction helps the digestion and provokes the terms. It also helps to strengthen the head and restores the body.", "res://assets/sprites/plants/Rockets.png"},
            {"Rosemary", PlanetaryHourCalculator::SUN, "Fire", "Governed by the Sun, it is an admirable remedy for all cold diseases of the head and brain. The decoction strengthens the memory and restores lost speech. It also helps to strengthen the head and comforts the spirits.", "res://assets/sprites/plants/Rosemary.png"},
            {"Rue", PlanetaryHourCalculator::SUN, "Fire", "Under the influence of the Sun in Leo, it is a singular remedy against poison and the plague. The decoction quickens the sight and is good for the ears. It also helps to strengthen the head and restores the body.", "res://assets/sprites/plants/Rue.png"},
            {"Sage", PlanetaryHourCalculator::JUPITER, "Air", "Governed by Jupiter, it is of singular use for the memory. The decoction warms and quickens the senses, and is excellent for all diseases of the joints. It also helps to strengthen the head and restores the spirits.", "res://assets/sprites/plants/Sage.png"},
            {"Samphire", PlanetaryHourCalculator::JUPITER, "Water", "An herb of Jupiter, it is a singular remedy for the stone and all diseases of the kidneys. The decoction helps the jaundice and provokes the terms. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Samphire.png"},
            {"Sanicle", PlanetaryHourCalculator::VENUS, "Water", "Under the dominion of Venus, it is a singular remedy for all kinds of wounds and sores. The decoction stays the fluxes and strengthens the stomach. It also helps to stay the humors and to strengthen the body.", "res://assets/sprites/plants/Sanicle.png"},
            {"Saracen's Confound", PlanetaryHourCalculator::SATURN, "Earth", "Governed by Saturn, it is a powerful remedy for all kinds of wounds and sores. The decoction stays the fluxes and strengthens the stomach. It also helps to stay the humors and to strengthen the body.", "res://assets/sprites/plants/Saracens-Confound.png"},
            {"Sauce-alone", PlanetaryHourCalculator::MERCURY, "Air", "Governed by Mercury, it is a singular remedy for the throat and to help the cough. The decoction helps the digestion and provokes the terms. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Sauce-alone.png"},
            {"Savory", PlanetaryHourCalculator::MERCURY, "Air", "Under the influence of Mercury, it is a singular remedy for the stomach and to stay the humors. The decoction helps the digestion and stays the vomiting. It also helps to strengthen the head and restores the body.", "res://assets/sprites/plants/Savory.png"},
            {"Scabious", PlanetaryHourCalculator::MERCURY, "Air", "Governed by Mercury, it is a singular remedy for all kinds of wounds and sores. The decoction helps the cough and all diseases of the lungs. It also helps to stay the humors and to strengthen the body.", "res://assets/sprites/plants/Scabious.png"},
            {"Scurvy-grass", PlanetaryHourCalculator::JUPITER, "Water", "An herb of Jupiter, it is a singular remedy for the scurvy and all diseases of the blood. The decoction helps the jaundice and the stone. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Scurvy-grass.png"},
            {"Self-heal", PlanetaryHourCalculator::VENUS, "Water", "Under the dominion of Venus, it is a singular remedy for all kinds of wounds and sores. The decoction stays the fluxes and strengthens the stomach. It also helps to stay the humors and to strengthen the body.", "res://assets/sprites/plants/Self-heal.png"},
            {"Service Tree", PlanetaryHourCalculator::SATURN, "Earth", "Governed by Saturn, the fruit is a singular remedy for all kinds of fluxes and to stay the humors. The decoction of the bark stays the bleeding and strengthens the stomach. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Service-Tree.png"},
            {"Shepherd's Purse", PlanetaryHourCalculator::SATURN, "Earth", "An herb of Saturn, it is a powerful remedy for all kinds of fluxes and to stay the humors. The decoction stays the bleeding and strengthens the stomach. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Shepherds-Purse.png"},
            {"Smallage", PlanetaryHourCalculator::MERCURY, "Air", "Governed by Mercury, it is a singular remedy for the stone and all diseases of the kidneys. The decoction helps the jaundice and provokes the terms. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Smallage.png"},
            {"Soapwort", PlanetaryHourCalculator::VENUS, "Water", "Under the dominion of Venus, it is a singular remedy for all kinds of wounds and sores. The decoction stays the fluxes and strengthens the stomach. It also helps to stay the humors and to strengthen the body.", "res://assets/sprites/plants/Soapwort.png"},
            {"Sorrel", PlanetaryHourCalculator::VENUS, "Water", "Governed by Venus, it is a singular remedy for the stomach and to stay the humors. The decoction helps the heat of the stomach and liver. It also helps to strengthen the head and restores the body.", "res://assets/sprites/plants/Sorrel.png"},
            {"Southernwood", PlanetaryHourCalculator::MERCURY, "Air", "An herb of Mercury, it is a singular remedy to kill worms and to help the cough. The decoction helps the stone and provokes the terms. It also helps to strengthen the head and restores the body.", "res://assets/sprites/plants/Southernwood.png"},
            {"Sow-thistle", PlanetaryHourCalculator::VENUS, "Water", "Governed by Venus, it is a singular remedy for all kinds of hot inflammations and to stay the humors. The decoction helps the heat of the stomach and liver. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Sow-thistle.png"},
            {"Spikenard", PlanetaryHourCalculator::VENUS, "Earth", "Under the dominion of Venus, it is a singular remedy for the stomach and to stay the humors. The decoction helps the digestion and provokes the terms. It also helps to strengthen the head and restores the body.", "res://assets/sprites/plants/Spikenard.png"},
            {"Spinach", PlanetaryHourCalculator::MOON, "Water", "Governed by the Moon, it is a singular remedy for all kinds of hot inflammations and to stay the humors. The decoction helps the heat of the stomach and liver. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Spinach.png"},
            {"Spurge", PlanetaryHourCalculator::MARS, "Fire", "An herb of Mars, it is a powerful remedy to provoke the terms and to help the cough. The decoction helps the stone and all diseases of the kidneys. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Spurge.png"},
            {"Squills", PlanetaryHourCalculator::MARS, "Fire", "Governed by Mars, it is a powerful remedy for the lungs and to help the cough. The decoction helps the jaundice and provokes the terms. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Squills.png"},
            {"St. John's Wort", PlanetaryHourCalculator::SUN, "Fire", "Under the celestial influence of the Sun and element of Fire, it is a singular wound herb. The decoction helps to clear melancholy and heals burns. It is also said to drive away evil spirits and comforts the heart.", "res://assets/sprites/plants/St.-Johns-Wort.png"},
            {"Star-thistle", PlanetaryHourCalculator::MARS, "Fire", "Governed by Mars, it is a powerful remedy for the stone and all diseases of the kidneys. The decoction helps the jaundice and provokes the terms. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Star-thistle.png"},
            {"Strawberries", PlanetaryHourCalculator::VENUS, "Water", "Under the influence of Venus under Leo, they are a singular remedy for the heart and to drive away melancholy. The decoction of the leaves helps the heat of the stomach and liver. It also helps to strengthen the head and restores the spirits.", "res://assets/sprites/plants/Strawberries.png"},
            {"Succory", PlanetaryHourCalculator::JUPITER, "Air", "Governed by Jupiter, it is a singular remedy for the liver and to help the yellow jaundice. The decoction helps all obstructions of the liver and spleen. It also helps to strengthen the head and stays the hot humors.", "res://assets/sprites/plants/Succory.png"},
            {"Tansy", PlanetaryHourCalculator::VENUS, "Air", "An herb of Venus, it is a singular remedy to kill worms and to stay the humors. The decoction helps the stone and provokes the terms. It also helps to strengthen the head and restores the body.", "res://assets/sprites/plants/Tansy.png"},
            {"Tarragon", PlanetaryHourCalculator::MARS, "Fire", "Governed by Mars, it is a powerful remedy to provoke the terms and to help the cough. The decoction helps the digestion and provokes the terms. It also helps to strengthen the head and restores the body.", "res://assets/sprites/plants/Tarragon.png"},
            {"Thistles", PlanetaryHourCalculator::MARS, "Fire", "Under the influence of Mars, they are a powerful remedy for the stone and all diseases of the kidneys. The decoction helps the jaundice and provokes the terms. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Thistles.png"},
            {"Thyme", PlanetaryHourCalculator::VENUS, "Air", "Governed by Venus, it is an excellent remedy for the lungs and to help the cough. The decoction helps to provoke the terms and eases the pains of the stomach. It also helps to strengthen the head and restores the spirits.", "res://assets/sprites/plants/Thyme.png"},
            {"Tobacco", PlanetaryHourCalculator::MARS, "Fire", "An herb of Mars, it is a powerful remedy against all kinds of poisons and the plague. The juice helps the bitings of mad dogs and serpents. It also helps to strengthen the head and restores the vital heat.", "res://assets/sprites/plants/Tobacco.png"},
            {"Tormentil", PlanetaryHourCalculator::SUN, "Fire", "Governed by the Sun, it is a singular remedy for all kinds of fluxes and to stay the humors. The decoction stays the bleeding and strengthens the stomach. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Tormentil.png"},
            {"Trefoil", PlanetaryHourCalculator::MOON, "Water", "Under the influence of the Moon, it is a singular remedy for all kinds of wounds and sores. The decoction stays the fluxes and strengthens the stomach. It also helps to stay the humors and to strengthen the body.", "res://assets/sprites/plants/Trefoil.png"},
            {"Turnips", PlanetaryHourCalculator::MOON, "Water", "Governed by the Moon, they are a singular remedy for the lungs and to help the cough. The decoction helps the digestion and provokes the terms. It also helps to strengthen the head and restores the body.", "res://assets/sprites/plants/Turnips.png"},
            {"Tutsan", PlanetaryHourCalculator::SUN, "Fire", "An herb of the Sun, it is a singular remedy for all kinds of wounds and sores. The decoction stays the fluxes and strengthens the stomach. It also helps to stay the humors and to strengthen the body.", "res://assets/sprites/plants/Tutsan.png"},
            {"Valerian", PlanetaryHourCalculator::MERCURY, "Air", "Governed by Mercury, it is a singular remedy for the nerves and to ease all pains of the head. The decoction helps to provoke the terms and stays the cough. It also helps to strengthen the head and restores the spirits.", "res://assets/sprites/plants/Valerian.png"},
            {"Vervain", PlanetaryHourCalculator::VENUS, "Earth", "Under the dominion of Venus, it is an excellent remedy for the stone and all diseases of the liver and spleen. The decoction helps the jaundice and provokes the terms. It also helps to strengthen the head and restores the body.", "res://assets/sprites/plants/Vervain.png"},
            {"Vine Tree", PlanetaryHourCalculator::SUN, "Water", "Governed by the Sun, the leaves are a singular remedy for all kinds of fluxes and to stay the humors. The decoction stays the bleeding and strengthens the stomach. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Vine-Tree.png"},
            {"Violets", PlanetaryHourCalculator::VENUS, "Water", "Under the dominion of Venus, they are a singular remedy for all kinds of pains and to stay the humors. The decoction helps the heat of the stomach and liver. It also helps to strengthen the head and restores the spirits.", "res://assets/sprites/plants/Violets.png"},
            {"Viper's Bugloss", PlanetaryHourCalculator::SUN, "Fire", "Governed by the Sun, it is a singular remedy against all kinds of poisons and the plague. The decoction helps the heart and drives away melancholy. It also helps to strengthen the head and restores the body.", "res://assets/sprites/plants/Vipers-Bugloss.png"},
            {"Wall-flowers", PlanetaryHourCalculator::MOON, "Water", "Under the influence of the Moon, they are a singular remedy for all kinds of pains and to stay the humors. The decoction helps the nerves and eases the pains of the head. It also helps to strengthen the head and restores the spirits.", "res://assets/sprites/plants/Wall-flowers.png"},
            {"Walnut Tree", PlanetaryHourCalculator::SUN, "Air", "Governed by the Sun, it is a singular remedy for the stomach and to stay the humors. The decoction of the bark stays the fluxes and strengthens the stomach. It also helps to strengthen the head and restores the body.", "res://assets/sprites/plants/Walnut-Tree.png"},
            {"Wheat", PlanetaryHourCalculator::VENUS, "Earth", "An herb of Venus, it is a singular remedy for all kinds of fluxes and to stay the humors. The decoction helps the heat of the stomach and liver. It also helps to strengthen the head and restores the body.", "res://assets/sprites/plants/Wheat.png"},
            {"Willow Tree", PlanetaryHourCalculator::MOON, "Water", "Governed by the Moon, it is a singular remedy for all kinds of fluxes and to stay the humors. The decoction stays the bleeding and strengthens the stomach. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Willow-Tree.png"},
            {"Wold", PlanetaryHourCalculator::MARS, "Fire", "Under the influence of Mars, it is a powerful remedy for the stone and to provoke the terms. The decoction helps the jaundice and provokes the terms. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Wold.png"},
            {"Wood Betony", PlanetaryHourCalculator::JUPITER, "Air", "Governed by Jupiter and the sign of Aries, it is a most precious herb. The decoction preserves the liver and bodies of men from the danger of epidemical diseases. It also helps to strengthen the head and shoulders.", "res://assets/sprites/plants/Wood-Betony.png"},
            {"Wood-ruff", PlanetaryHourCalculator::MARS, "Fire", "An herb of Mars, it is a powerful remedy for the stone and all diseases of the kidneys. The decoction helps the jaundice and provokes the terms. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Wood-ruff.png"},
            {"Wood-sage", PlanetaryHourCalculator::JUPITER, "Air", "Governed by Jupiter, it is a singular remedy for all kinds of wounds and sores. The decoction stays the fluxes and strengthens the stomach. It also helps to stay the humors and to strengthen the body.", "res://assets/sprites/plants/Wood-sage.png"},
            {"Wood-sorrel", PlanetaryHourCalculator::VENUS, "Water", "Under the dominion of Venus, it is a singular remedy for the stomach and to stay the humors. The decoction helps the heat of the stomach and liver. It also helps to strengthen the head and restores the body.", "res://assets/sprites/plants/Wood-sorrel.png"},
            {"Wormwood", PlanetaryHourCalculator::MARS, "Fire", "Governed by Mars, it is a singular remedy for the stomach and to kill worms. The decoction helps the digestion and stays the vomiting. It also helps against the biting of rats and mice.", "res://assets/sprites/plants/Wormwood.png"},
            {"Yarrow", PlanetaryHourCalculator::VENUS, "Earth", "Under the dominion of Venus and placed under the Earth element, it is an excellent styptic wound herb. The decoction stops bleeding and opens pores to relieve fevers. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Yarrow.png"},
            {"Yellow Rattle", PlanetaryHourCalculator::MARS, "Fire", "Governed by Mars, it is a powerful remedy for the stone and to provoke the terms. The decoction helps the cough and all diseases of the lungs. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Yellow-Rattle.png"},
            {"Yellow Wall-flower", PlanetaryHourCalculator::MOON, "Water", "Under the influence of the Moon, it is a singular remedy for all kinds of pains and to stay the humors. The decoction helps the nerves and eases the pains of the head. It also helps to strengthen the head and restores the spirits.", "res://assets/sprites/plants/Yellow-Wall-flower.png"},
            {"Yew", PlanetaryHourCalculator::SATURN, "Earth", "Governed by Saturn, it is a powerful remedy for all kinds of pains and to stay the humors. The decoction stays the bleeding and strengthens the stomach. It also helps to strengthen the head and stays the humors.", "res://assets/sprites/plants/Yew.png"},
            {"Zeodary", PlanetaryHourCalculator::MARS, "Fire", "Governed by Mars, it is a powerful remedy against all kinds of poisons and the plague. The decoction helps the digestion and provokes the terms. It also helps to strengthen the head and restores the vital heat.", "res://assets/sprites/plants/Zeodary.png"}
        };

        for (const auto& r : raw) {
            Ref<PlantData> p;
            p.instantiate();
            p->name = r.name;
            p->ruler = r.ruler;
            p->element = r.element;
            p->properties = r.props;
            p->sprite_path = r.sprite;
            entries.append(p);
        }

        return entries;
    }
}

void PlantDatabase::_bind_methods() {
    ClassDB::bind_static_method("PlantDatabase", D_METHOD("get_plant", "name"), &PlantDatabase::get_plant);
    ClassDB::bind_static_method("PlantDatabase", D_METHOD("get_all_plants"), &PlantDatabase::get_all_plants);
}

Ref<PlantData> PlantDatabase::get_plant(const String& p_name) {
    TypedArray<PlantData> all = get_botanical_entries();
    for (int i = 0; i < all.size(); i++) {
        Ref<PlantData> p = all[i];
        if (p->name == p_name) return p;
    }
    return Ref<PlantData>();
}

TypedArray<PlantData> PlantDatabase::get_all_plants() {
    return get_botanical_entries();
}

} // namespace godot
